name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' 

      - name: Install dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish the project
        run: dotnet publish ./MyBudgetManagerAPI.csproj -c Release -o ./output

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp://155.254.244.37
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /output/
          server-dir: //www.MyBudgetManagerAPI.somee.com/
      
