name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' 

      - name: Install dependencies
        run: dotnet restore ./MyBudgetManagerAPI/MyBudgetManagerAPI.sln # Restore dependencies for the solution

      - name: Build the solution
        run: dotnet build ./MyBudgetManagerAPI/MyBudgetManagerAPI.sln --configuration Release --no-restore # Build the solution

      - name: Run unit tests
        run: dotnet test ./MyBudgetManagerAPI.Tests/MyBudgetManagerAPI.Tests.csproj --no-restore --verbosity normal # Run tests from the test project

      - name: Publish the project
        run: dotnet publish ./MyBudgetManagerAPI/MyBudgetManagerAPI.csproj -c Release -o ./output
        
      - name: List Output Directory for Debugging
        run: ls -al ./output # Verifies if output is generated properly
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./output

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 155.254.244.37
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./output/
          server-dir: www.MyBudgetManagerAPI.somee.com/
